/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three"
import React, { useEffect, useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { GLTF } from "three-stdlib"
import { useSnapshot } from "valtio"
import { partsName } from "@constants/preHaus"
import { bootsColorState } from "./PreHausCustomization"

type GLTFResult = GLTF & {
  nodes: {
    [keys: string]: THREE.Mesh
  }
  materials: {
    [keys: string]: THREE.MeshStandardMaterial
  }
}

export default function BootsBody({ ...props }: any) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF(
    "assets/boots/NFT_BOOTS_BODY.glb"
  ) as GLTFResult

  const snap = useSnapshot(bootsColorState)
  // console.log("bootsColorState : ", bootsColorState)

  // useEffect(() => {
  //   console.log("snap.parts.Quarter : ", snap.parts.Quarter)
  //   console.log("snap.parts.Vamp : ", snap.parts.Vamp)
  //   console.log("snap.parts.Lace : ", snap.parts.Lace)
  //   console.log('snap.parts["Back Counter"] : ', snap.parts["Back Counter"])
  //   console.log('snap.parts["Pull Loops"] : ', snap.parts["Pull Loops"])
  // }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      {/* Quarter */}
      <mesh
        castShadow
        // receiveShadow
        geometry={nodes[partsName.Quarter].geometry}
        material={materials[partsName.Quarter]}
        rotation={[-Math.PI / 2, 0, 0]}
        material-color={snap.parts.Quarter ?? "#fff"}
      />

      {/* Vamp */}
      <mesh
        castShadow
        // receiveShadow
        geometry={nodes[partsName.Vamp].geometry}
        material={materials[partsName.Vamp]}
        rotation={[-Math.PI / 2, 0, 0]}
        material-color={snap.parts.Vamp ?? "#fff"}
      />
      {/* Lace */}
      <mesh
        castShadow
        // receiveShadow
        geometry={nodes[partsName.Lace].geometry}
        material={materials[partsName.Lace]}
        rotation={[-Math.PI / 2, 0, 0]}
        material-color={snap.parts.Lace ?? "#fff"}
      />

      {/* Back Counter */}
      <mesh
        castShadow
        // receiveShadow
        geometry={nodes[partsName["Back Counter"]].geometry}
        material={materials[partsName["Back Counter"]]}
        rotation={[-Math.PI / 2, 0, 0]}
        material-color={snap.parts["Back Counter"] ?? "#fff"}
      />

      {/* Pull loops */}
      <mesh
        castShadow
        // receiveShadow
        geometry={nodes[partsName["Pull Loops"]].geometry}
        material={materials[partsName["Pull Loops"]]}
        rotation={[-Math.PI / 2, 0, 0]}
        material-color={snap.parts["Pull Loops"] ?? "#fff"}
      />
    </group>
  )
}

useGLTF.preload("assets/boots/NFT_BOOTS_BODY.glb")
